[package]
name = "websocket-server"
version.workspace = true
edition.workspace = true

[dependencies]
realm-server = { workspace = true }
tokio = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
anyhow = { workspace = true }
